<a href="https://colab.research.google.com/github/joelinho10/Inteligencia-Artificial/blob/main/Exploring_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

Erik Joel Olmedo Zambrano

In [1]:
# Import numpy as np and see the version
# your code here
import numpy as np
print (np.__version__)

1.23.5


In [2]:
# Create a 1D array of numbers from 0 to 9
# your code here
a = np.arange(10)
print (a)
print (a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
# Create random vector of size 10 and replace the maximum value by 0
b = np.random.randint(1,11,[10])
print (b)
maxnum = np.argmax(b)
b[maxnum] = 0
print (b)
print (b.shape)

[ 5  3  9 10  4  5  2  8  5 10]
[ 5  3  9  0  4  5  2  8  5 10]
(10,)


In [4]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print (arr[1,2])

8


In [5]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print (arr[2:5])

[3 4 5]


In [6]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print (arr[3:9])

[4 5 6 7]


In [7]:
# Create a 3×3 numpy array of all True’s
# your code here
arr = np.ones((3,3), dtype=bool)
print (arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
# Extract all odd numbers from arr
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[ True  True  True  True  True  True  True  True  True]


In [10]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# Reverse a vector (first element becomes last)
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
#  Create a 10x10 array with random integer values and find the minimum and maximum values
random_10x10 = np.random.randint(0, 100, (10, 10))
print(random_10x10)
print("Minimum value:", np.min(random_10x10))
print("Maximum value:", np.max(random_10x10))

[[54 77 49 61 60 38 90 55  9 54]
 [47 52 29 73 31 66 50 62 15 83]
 [48 38 24 13 24 14 19 20  5 62]
 [72 87 93  8 74  3 24 64 39 65]
 [70 84 43  6 48 78  9 67 68  4]
 [19 26 50 34 84 44  1 43 25 55]
 [39 69 21 79 39 70  8 21 51 82]
 [67 35 80 17 14 24 30 71 13 62]
 [18 81 56 74 28 21 43 42 51 26]
 [29  1  5 55 47 88 28 91 78 80]]
Minimum value: 1
Maximum value: 93


In [13]:
# Create a 3x3x3 array with random values
random3 = np.random.random((3, 3, 3))
print(random3)

[[[0.51287491 0.58689184 0.70682038]
  [0.62217944 0.77403818 0.23334841]
  [0.12902261 0.43621465 0.28903739]]

 [[0.43084977 0.70401558 0.92660588]
  [0.42105304 0.55744122 0.44616483]
  [0.45751455 0.38982707 0.18290525]]

 [[0.74117303 0.06730122 0.5885356 ]
  [0.19751412 0.7563722  0.66028906]
  [0.7857272  0.24972978 0.30430157]]]


In [14]:
# Replace all odd numbers in arr with -1
# your code here
arr[arr % 2 != 0] = -1
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [15]:
# Create an array of type float
float_arr = np.array([1.0, 2.5, 3.7], dtype=float)
print(float_arr)

[1.  2.5 3.7]


In [16]:
# Convert a 1D array to a 2D array with 2 rows
# your code here
arr_1d = np.arange(6)
arr_2d = arr_1d.reshape(2, -1)
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [17]:
# How to find common values between two arrays?

# Z1 = np.random.randint(0,10,10)
# Z2 = np.random.randint(0,10,10)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0, 10, 10)
print (Z1, Z2)
common_values = np.intersect1d(Z1, Z2)
print(common_values)

[8 8 4 4 9 6 1 1 3 5] [0 1 5 7 3 8 0 1 4 8]
[1 3 4 5 8]


In [18]:
#  Consider two random array A and B, check if they are equal


# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print (A, B)
are_equal = np.array_equal(A, B)
print(are_equal)

[1 1 1 1 1] [0 1 1 1 1]
False


In [19]:
# Stack arrays a and b vertically
# your code here
stacked_arrays = np.vstack((A, B))
print(stacked_arrays)

[[1 1 1 1 1]
 [0 1 1 1 1]]


In [20]:
# Stack the arrays a and b horizontally.
# your code here
stacked_arrays = np.hstack((A, B))
print(stacked_arrays)

[1 1 1 1 1 0 1 1 1 1]


In [21]:
# Get all items between 5 and 10 from array tmp.
# your code here
tmp = np.array([1, 6, 11, 7, 9, 3, 14])
selected_items = tmp[(tmp >= 5) & (tmp <= 10)]
print(selected_items)

[6 7 9]


In [22]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
def pair_max(a, b):
    return np.maximum(a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [23]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr[:, [1, 2]] = arr[:, [2, 1]]
print(arr)


[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [24]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_decimal_5_10 = np.random.uniform(5, 10, (5, 3))
print(random_decimal_5_10)

[[9.5535905  5.85740105 5.54453574]
 [5.0749996  9.37401207 7.53709345]
 [8.83748767 6.26634568 9.11800437]
 [5.73507837 5.2793283  7.7000172 ]
 [8.27682269 7.2768376  8.35099718]]
