<a href="https://colab.research.google.com/github/joelinho10/Inteligencia-Artificial/blob/main/Numpy_Library_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from numpy.random import MT19937
import numpy as np
print ("Matriz 1")
m1 = np.random.randint(1,11,[3,4])
print (m1)
print (m1.shape)
print ("Matriz 2")
m2 = np.random.randint(1,11,[3,4])
print (m2)
print (m2.shape)
print ("Suma de matrices")
print (m1 + m2)
print ("Resta de matrices")
print (m1 - m2)
print ("Multiplicacion de matrices")
print (m1 * m2)

Matriz 1
[[ 8  4  1 10]
 [ 2  2  3  4]
 [ 2  7  3  2]]
(3, 4)
Matriz 2
[[ 8  9  9  3]
 [ 3 10  7  4]
 [ 5  5  6  6]]
(3, 4)
Suma de matrices
[[16 13 10 13]
 [ 5 12 10  8]
 [ 7 12  9  8]]
Resta de matrices
[[ 0 -5 -8  7]
 [-1 -8 -4  0]
 [-3  2 -3 -4]]
Multiplicacion de matrices
[[64 36  9 30]
 [ 6 20 21 16]
 [10 35 18 12]]


In [17]:
print ("Suma de matrices")
print (np.add(m1,m2))
print ("Resta de matrices")
print (np.subtract(m1,m2))
print ("Multiplicacion de matrices")
print (np.multiply(m1,m2))
print ("Division de matrices")
print (np.divide(m1,m2))

Suma de matrices
[[16 13 10 13]
 [ 5 12 10  8]
 [ 7 12  9  8]]
Resta de matrices
[[ 0 -5 -8  7]
 [-1 -8 -4  0]
 [-3  2 -3 -4]]
Multiplicacion de matrices
[[64 36  9 30]
 [ 6 20 21 16]
 [10 35 18 12]]
Division de matrices
[[1.         0.44444444 0.11111111 3.33333333]
 [0.66666667 0.2        0.42857143 1.        ]
 [0.4        1.4        0.5        0.33333333]]


In [18]:
print ("Matriz 1")
m3 = np.random.randint(1,11,[3,4])
print (m3)
print (m3.shape)
print ("Matriz 2")
m4 = np.random.randint(1,11,[4,3])
print (m4)
print (m4.shape)

print (np.dot(m3,m4))

Matriz 1
[[8 3 4 8]
 [4 8 6 5]
 [1 1 5 5]]
(3, 4)
Matriz 2
[[ 1  3  2]
 [ 4  4  6]
 [ 8  1  6]
 [10  5 10]]
(4, 3)
[[132  80 138]
 [134  75 142]
 [ 95  37  88]]


In [19]:
print ("Matriz 1")
m5 = np.random.randint(1,11,[2,2])
print (m5.shape)
print (type (m5))
print (m5)
print (m5.T)

Matriz 1
(2, 2)
<class 'numpy.ndarray'>
[[3 1]
 [8 8]]
[[3 8]
 [1 8]]


In [20]:
print ("Matriz 1")
m6 = np.random.randint(1,11,[4,3])
m7 = np.array([1,0,2])
print (m6.shape)
print (m7.shape)
m8 = np.empty_like(m6)
print (m6)
print (m7)
print (m8.shape)
print (m8)

Matriz 1
(4, 3)
(3,)
[[ 2  3  3]
 [ 7 10  1]
 [ 8  8  6]
 [ 9  9 10]]
[1 0 2]
(4, 3)
[[ 1 10  3]
 [ 2 10 10]
 [ 7  7  2]
 [ 2  6 10]]


In [7]:
for i in range(4):
  m8[i,:]= m6[i,:]+m7
print (m6)
print (m7)
print (m8)

[[ 3  8  9]
 [ 8  5  4]
 [ 9  9  8]
 [ 3 10 10]]
[1 0 2]
[[ 4  8 11]
 [ 9  5  6]
 [10  9 10]
 [ 4 10 12]]


In [8]:
a = np.array([1,2,3])
print (a)
b = np.tile(a,(6,1))
print (b)
print (b.shape)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(6, 3)


In [9]:
m1 = np.random.randint(20,30,[6,6])
print (m1)

[[23 22 24 22 23 22]
 [29 24 24 22 22 24]
 [25 27 24 24 22 22]
 [27 21 21 26 27 24]
 [21 20 23 25 24 21]
 [29 22 27 23 27 27]]


In [12]:
print('Matriz A')
A = np.array([1,2,3])

print(A)

print(' ')
print('----------------------------------------------------------')
print(' ')

print('Matriz B')
B = np.array([1,2,3])
matriz = np.tile(B, (6, 1))
print(matriz)

print(' ')
print('---------------------------------------------------------')
print(' ')

print('Matriz C')
C = np.random.randint(0, 11, size=(6, 6))
print(C)
promedio = np.mean(C)
print(' ')
print('Promedio')
print(promedio)

print(' ')
print('------------------------------------------------------------')
print(' ')

promedio1 = np.mean(C, axis=1)
print(' ')
print('Promedio por filas')
print(promedio1)

print(' ')
print('-------------------------------------------------------------')
print(' ')

promedio2 = np.mean(C, axis=0)
print(' ')
print('Promedio por columnas')
print(promedio2)

Matriz A
[1 2 3]
 
----------------------------------------------------------
 
Matriz B
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
 
---------------------------------------------------------
 
Matriz C
[[ 7 10  3  9  1  6]
 [10  8  9  0  1  4]
 [ 6  5  8  5  7 10]
 [ 6  7  8 10  2  1]
 [ 8  1  0  9  5  4]
 [ 3  5  5  7  4  7]]
 
Promedio
5.583333333333333
 
------------------------------------------------------------
 
 
Promedio por filas
[6.         5.33333333 6.83333333 5.66666667 4.5        5.16666667]
 
-------------------------------------------------------------
 
 
Promedio por columnas
[6.66666667 6.         5.5        6.66666667 3.33333333 5.33333333]
