<a href="https://colab.research.google.com/github/joelinho10/Inteligencia-Artificial/blob/main/Numpy_Library_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

aux = np.array([1,2,4,5])
print(aux)
print(aux.shape)
aux = np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
tmp = np.zeros([4,4])
print (tmp)
tmp = np.full([4,4],5)
print (tmp)
tmp = np.eye(4,4)
print (tmp)
tmp = np.ones([4,4])
print (tmp)
print (tmp.shape)
tmp = 10*np.random.random([3,3])
print (tmp)

[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
[[8.72353022 8.48055555 5.07888002]
 [9.23173535 0.56365013 3.07645065]
 [2.93583318 4.38124842 1.0202041 ]]


In [2]:
tmp = 10*np.random.random([3,3])
print (tmp)

[[2.4762185  0.56987862 2.07195311]
 [5.37325717 6.92609307 5.61517262]
 [3.76360205 0.2113081  9.51459267]]


In [3]:
print (tmp[:2,:2])

[[2.4762185  0.56987862]
 [5.37325717 6.92609307]]


In [4]:
print (tmp[:2,1:3])

[[0.56987862 2.07195311]
 [6.92609307 5.61517262]]


In [5]:
print (tmp [2,2])

9.514592669718619


Filtrar valores con mask

In [7]:
mask = tmp>5
print (tmp[mask])

[5.37325717 6.92609307 5.61517262 9.51459267]


In [8]:
mask = (tmp>=2) & (tmp<=4)
print (tmp[mask])

[2.4762185  2.07195311 3.76360205]


In [9]:
tmp = np.random.randint(0,10,[4,4])
print (tmp)

[[5 5 4 2]
 [0 2 7 1]
 [1 4 3 2]
 [1 0 8 0]]


Extraer numeros pares

In [10]:
nrosEnteros = np.random.randint(0, 10, size=(4, 4))
print(nrosEnteros)


print('---------------------------')
nrosEnteros = nrosEnteros[nrosEnteros % 2 == 0]
print(nrosEnteros)


[[5 1 9 7]
 [3 0 8 8]
 [2 9 1 1]
 [5 6 3 5]]
---------------------------
[0 8 8 2 6]
